-- Фактическая схема БД бота (создана в Table Editor).
-- unique на user_telegram_id обязателен для upsert клиента из бота.

create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_telegram_id character varying null,
  first_name character varying null,
  last_name character varying null,
  last_message_at timestamp without time zone not null,
  constraint clients_pkey primary key (id),
  constraint clients_user_telegram_id_key unique (user_telegram_id)
);

create table public.messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  author character varying null,
  body text null,
  messenger_user_id character varying null,
  messenger_type character varying null,
  client_id bigint null,
  constraint messages_pkey primary key (id),
  constraint messages_client_id_fkey foreign key (client_id) references public.clients (id)
);

create index if not exists messages_created_at_idx on public.messages (created_at desc);
create index if not exists clients_last_message_at_idx on public.clients (last_message_at desc);
